spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://vigoikstest.service-now.com/oauth_token.do
        registration:
          egrunnerverv:
            authorization-grant-type: password
            provider: fint-idp
            client-id: ${fint.flyt.egrunnerverv.client-id}
            client-secret: ${fint.flyt.egrunnerverv.client-secret}
  profiles:
    include:
      - flyt-kafka
      - flyt-postgres

fint:
  application-id: fint-flyt-egrunnerverv-dispatch-gateway
  flyt:
    egrunnerverv:
      retentionTimeInDays: 30
      username:
      password:
      client-id:
      client-secret:
      registrationId: egrunnerverv
      base-url: https://vigoikstest.service-now.com/api/now/table
      instance-dispatch-interval-cron: "0 0/30 * * * *"
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus