fint:
  org-id: fintlabs.no
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5439/fint-flyt-egrunnerverv-dispatch-gateway
    username: postgres
    password: password

logging:
  level:
    no.fintlabs: DEBUG
    org.springframework.web.reactive: DEBUG

server:
  port: 8093