spring:
  security:
    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://vigoikstest.service-now.com/oauth_token.do
        registration:
          egrunnerverv:
            authorization-grant-type: password
            provider: fint-idp
            client-id:
            client-secret:
  profiles:
    include:
      - flyt-kafka
      - flyt-postgres

fint:
  application-id: fint-flyt-egrunnerverv-dispatch-gateway
  flyt:
    egrunnerverv:
      retentionTimeInDays: 30
      username:
      password:
      registrationId: egrunnerverv
      base-url: https://vigoikstest.service-now.comm/api/now/table
      instance-dispatch-interval-cron: 0 0 0 * * *
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus