fint:
  org-id: fintlabs.no
  kafka:
    default-replicas: 1
  flyt:
    egrunnerverv:
      base-url: https://vigoikstest.service-now.com/api/now/table
      token-uri: https://vigoikstest.service-now.com/oauth_token.do
      instance-dispatch-initial-delay: 20000
      instance-dispatch-fixed-delay: 10000
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5439/fint-flyt-egrunnerverv-dispatch-gateway
    username: postgres
    password: password
    hikari:
      schema: fintlabs_no

logging:
  level:
    no.fintlabs: DEBUG
    org.springframework.web.reactive: DEBUG

server:
  port: 8093