fint:
  org-id: fintlabs.no
  flyt:
    resource-server:
      security:
        api:
          internal:
            enabled: true
            authorized-org-ids: 'viken.no, vigo.no'

  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    no.fintlabs: DEBUG
    org.springframework.web.reactive: DEBUG

server:
  port: 8093