apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-flyt-egrunnerverv-dispatch-gateway
data:
  TZ: 'Europe/Oslo'
  JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  fint.org-id: 'vlfk.no'
  fint.flyt.egrunnerverv.base-url: 'https://vigoikstest.service-now.com/api/now/table'